version: "3.0"

services:
  web:
    build: .
    volumes:
      - .:/app
    environment:
      APP_NAME: ${APP_NAME}
      APP_VERSION: ${APP_VERSION}
      APP_DESCRIPTION: ${APP_DESCRIPTION}
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      APP_ENV: ${APP_ENV}
      SECRET_KEY: ${SECRET_KEY}
      DB_SECRET_KEY: ${DB_SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_EXPIRY: ${JWT_EXPIRY}
      JWT_REFRESH_EXPIRY: ${JWT_REFRESH_EXPIRY}
      DB_REDIS_HOST: ${DB_REDIS_HOST}
      DB_REDIS_PORT: ${DB_REDIS_PORT}
      DB_REDIS_PASSWORD: ${DB_REDIS_PASSWORD}
      DB_DRIVER: ${DB_DRIVER}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:6
    ports:
      - "4001:6379"
    environment:
      REDIS_PASSWORD: ${DB_REDIS_PASSWORD}
    networks:
      - app-network

  celery:
    build: .
    command: celery -A src.celery_tasks.c_app worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      DB_REDIS_HOST: ${DB_REDIS_HOST}
      DB_REDIS_PORT: ${DB_REDIS_PORT}
      DB_REDIS_PASSWORD: ${DB_REDIS_PASSWORD}
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
