# sync/seeders/mst_permissions_seeder.py
# -*- coding: utf-8 -*-
# Copyright 2024 - Ika Raya Sentausa

table = "mst_permissions"


async def seed(engine):
    f"""Insert initial data into {table} table"""
    query = f"""
    INSERT INTO {table} (name, description) VALUES
    ('manage:auth', 'Manage authentication permission'),
    ('switch:auth', 'Switch authentication permission'),
    ('manage:audit-logs', 'Manage audit logs permission'),
    ('view:audit-logs', 'View audit logs permission'),
    ('show:audit-logs', 'Show audit logs permission'),
    ('manage:users', 'Manage users permission'),
    ('view:users', 'View users permission'),
    ('show:users', 'Show users permission'),
    ('select:users', 'Select users permission'),
    ('create:users', 'Create users permission'),
    ('update:users', 'Update users permission'),
    ('assign:roles', 'Assign roles permission'),
    ('revoke:roles', 'Revoke roles permission'),
    ('grant:user-permissions', 'Assign permissions permission'),
    ('revoke:user-permissions', 'Revoke permissions permission'),
    ('inactive:users', 'Inactive users permission'),
    ('active:users', 'Active users permission'),
    ('manage:roles', 'Manage roles permission'),
    ('view:roles', 'View roles permission'),
    ('show:roles', 'Show roles permission'),
    ('select:roles', 'Select roles permission'),
    ('create:roles', 'Create roles permission'),
    ('update:roles', 'Update roles permission'),
    ('grant:role-permissions', 'Assign permissions permission'),
    ('revoke:role-permissions', 'Revoke permissions permission'),
    ('delete:roles', 'Delete roles permission'),
    ('trash:roles', 'Trash roles permission'),
    ('restore:roles', 'Restore roles permission'),
    ('manage:permissions', 'Manage permissions permission'),
    ('view:permissions', 'View permissions permission'),
    ('show:permissions', 'Show permissions permission'),
    ('select:permissions', 'Select permissions permission'),
    ('create:permissions', 'Create permissions permission'),
    ('update:permissions', 'Update permissions permission'),
    ('delete:permissions', 'Delete permissions permission'),
    ('trash:permissions', 'Trash permissions permission'),
    ('restore:permissions', 'Restore permissions permission'),
    ('manage:menus', 'Manage menus permission'),
    ('view:menus', 'View menus permission'),
    ('show:menus', 'Show menus permission'),
    ('select:menus', 'Select menus permission'),
    ('create:menus', 'Create menus permission'),
    ('update:menus', 'Update menus permission'),
    ('grant:role-menus', 'Assign menus permission'),
    ('revoke:role-menus', 'Revoke menus permission'),
    ('grant:user-menus', 'Assign menus permission'),
    ('revoke:user-menus', 'Revoke menus permission'),
    ('delete:menus', 'Delete menus permission'),
    ('trash:menus', 'Trash menus permission'),
    ('restore:menus', 'Restore menus permission'),
    ('hierarchy:menus', 'Hierarchy menus permission'),
    ('manage:actions', 'Manage actions permission'),
    ('view:actions', 'View actions permission'),
    ('show:actions', 'Show actions permission'),
    ('create:actions', 'Create actions permission'),
    ('update:actions', 'Update actions permission'),
    ('delete:actions', 'Delete actions permission'),
    ('trash:actions', 'Trash actions permission'),
    ('restore:actions', 'Restore actions permission'),
    ('color:actions', 'Color actions permission'),
    ('manage:account-categories', 'Manage account categories permission'),
    ('view:account-categories', 'View account categories permission'),
    ('show:account-categories', 'Show account categories permission'),
    ('select:account-categories', 'Select account categories permission'),
    ('create:account-categories', 'Create account categories permission'),
    ('update:account-categories', 'Update account categories permission'),
    ('delete:account-categories', 'Delete account categories permission'),
    ('trash:account-categories', 'Trash account categories permission'),
    ('restore:account-categories', 'Restore account categories permission'),
    ('manage:account-levels', 'Manage account levels permission'),
    ('view:account-levels', 'View account levels permission'),
    ('show:account-levels', 'Show account levels permission'),
    ('select:account-levels', 'Select account levels permission'),
    ('create:account-levels', 'Create account levels permission'),
    ('update:account-levels', 'Update account levels permission'),
    ('delete:account-levels', 'Delete account levels permission'),
    ('trash:account-levels', 'Trash account levels permission'),
    ('restore:account-levels', 'Restore account levels permission'),
    ('manage:account-tags', 'Manage account tags permission'),
    ('view:account-tags', 'View account tags permission'),
    ('show:account-tags', 'Show account tags permission'),
    ('select:account-tags', 'Select account tags permission'),
    ('create:account-tags', 'Create account tags permission'),
    ('update:account-tags', 'Update account tags permission'),
    ('delete:account-tags', 'Delete account tags permission'),
    ('trash:account-tags', 'Trash account tags permission'),
    ('restore:account-tags', 'Restore account tags permission'),
    ('manage:account-types', 'Manage account types permission'),
    ('view:account-types', 'View account types permission'),
    ('show:account-types', 'Show account types permission'),
    ('select:account-types', 'Select account types permission'),
    ('create:account-types', 'Create account types permission'),
    ('update:account-types', 'Update account types permission'),
    ('delete:account-types', 'Delete account types permission'),
    ('trash:account-types', 'Trash account types permission'),
    ('restore:account-types', 'Restore account types permission'),
    ('manage:analytic-accounts', 'Manage analytic accounts permission'),
    ('view:analytic-accounts', 'View analytic accounts permission'),
    ('show:analytic-accounts', 'Show analytic accounts permission'),
    ('select:analytic-accounts', 'Select analytic accounts permission'),
    ('create:analytic-accounts', 'Create analytic accounts permission'),
    ('update:analytic-accounts', 'Update analytic accounts permission'),
    ('delete:analytic-accounts', 'Delete analytic accounts permission'),
    ('trash:analytic-accounts', 'Trash analytic accounts permission'),
    ('restore:analytic-accounts', 'Restore analytic accounts permission'),
    ('manage:accounts', 'Manage accounts permission'),
    ('view:accounts', 'View accounts permission'),
    ('show:accounts', 'Show accounts permission'),
    ('select:accounts', 'Select accounts permission'),
    ('create:accounts', 'Create accounts permission'),
    ('update:accounts', 'Update accounts permission'),
    ('delete:accounts', 'Delete accounts permission'),
    ('trash:accounts', 'Trash accounts permission'),
    ('restore:accounts', 'Restore accounts permission'),
    ('hierarchy:accounts', 'Hierarchy accounts permission'),
    ('manage:currencies', 'Manage currencies permission'),
    ('view:currencies', 'View currencies permission'),
    ('show:currencies', 'Show currencies permission'),
    ('select:currencies', 'Select currencies permission'),
    ('create:currencies', 'Create currencies permission'),
    ('update:currencies', 'Update currencies permission'),
    ('delete:currencies', 'Delete currencies permission'),
    ('trash:currencies', 'Trash currencies permission'),
    ('restore:currencies', 'Restore currencies permission'),
    ('manage:taxes', 'Manage taxes permission'),
    ('view:taxes', 'View taxes permission'),
    ('show:taxes', 'Show taxes permission'),
    ('select:taxes', 'Select taxes permission'),
    ('create:taxes', 'Create taxes permission'),
    ('update:taxes', 'Update taxes permission'),
    ('delete:taxes', 'Delete taxes permission'),
    ('trash:taxes', 'Trash taxes permission'),
    ('restore:taxes', 'Restore taxes permission'),
    ('manage:journal-types', 'Manage journal types permission'),
    ('view:journal-types', 'View journal types permission'),
    ('show:journal-types', 'Show journal types permission'),
    ('select:journal-types', 'Select journal types permission'),
    ('create:journal-types', 'Create journal types permission'),
    ('update:journal-types', 'Update journal types permission'),
    ('delete:journal-types', 'Delete journal types permission'),
    ('trash:journal-types', 'Trash journal types permission'),
    ('restore:journal-types', 'Restore journal types permission'),
    ('manage:journals', 'Manage journals permission'),
    ('view:journals', 'View journals permission'),
    ('show:journals', 'Show journals permission'),
    ('select:journals', 'Select journals permission'),
    ('create:journals', 'Create journals permission'),
    ('update:journals', 'Update journals permission'),
    ('delete:journals', 'Delete journals permission'),
    ('trash:journals', 'Trash journals permission'),
    ('restore:journals', 'Restore journals permission'),
    ('manage:journals', 'Manage journal entries permission'),
    ('view:journal-entries', 'View journal entries permission'),
    ('show:journal-entries', 'Show journal entries permission'),
    ('create:journal-entries', 'Create journal entries permission'),
    ('update:journal-entries', 'Update journal entries permission'),
    ('posting:journal-entries', 'Posting journal entries permission'),
    ('delete:journal-entries', 'Delete journal entries permission'),
    ('trash:journal-entries', 'Trash journal entries permission'),
    ('restore:journal-entries', 'Restore journal entries permission'),
    ('manage:journals', 'Manage cash funds permission'),
    ('view:cash-funds', 'View cash funds permission'),
    ('show:cash-funds', 'Show cash funds permission'),
    ('create:cash-funds', 'Create cash funds permission'),
    ('update:cash-funds', 'Update cash funds permission'),
    ('publish:cash-funds', 'Publish cash funds permission'),
    ('delete:cash-funds', 'Delete cash funds permission'),
    ('trash:cash-funds', 'Trash cash funds permission'),
    ('restore:cash-funds', 'Restore cash funds permission');
    """
    await engine.execute(query)


async def rollback(engine):
    f"""Clear all data from {table} table"""
    query = f"TRUNCATE TABLE {table};"
    await engine.execute(query)
